apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: audit-zone
spec:
  volumes:
    - name: host
      hostPath:
        path: /var/log
        type: Directory
  containers:
    - name: busybox
      image: busybox:1.36
      command: [ "sh", "-c", "sleep 3600" ]
      volumeMounts:
        - name: host
          mountPath: /host-logs
