apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "deployments" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "statefulsets" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "configmaps", "secrets" ]
    verbs: [ "get", "list", "watch" ]
