apiVersion: v1
kind: Namespace
metadata:
  name: work
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: work
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: work
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: work
