apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHostPathProhibited
metadata:
  name: disallow-hostpath
spec:
  match:
    kinds:
      - apiGroups: [ "" ]
        kinds: [ "Pod" ]
    namespaces: [ "audit-zone" ]
