apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: RequestResponse
    namespaces: [ "audit-zone" ]
    verbs: [ "create", "update", "patch", "delete" ]
    resources:
      - group: ""
        resources: [ "pods" ]

  - level: Metadata
    verbs: [ "create" ]
    resources:
      - group: ""
        resources: [ "pods" ]
    namespaceSelector:
      matchLabels:
        pod-security.kubernetes.io/enforce: "restricted"

  - level: RequestResponse
    verbs: [ "create", "update", "patch", "delete" ]
    resources:
      - group: "rbac.authorization.k8s.io"
        resources: [ "roles", "rolebindings", "clusterroles", "clusterrolebindings" ]

  - level: RequestResponse
    verbs: [ "create", "update", "patch", "delete" ]
    resources:
      - group: "templates.gatekeeper.sh"
        resources: [ "constrainttemplates" ]
      - group: "constraints.gatekeeper.sh"
        resources: [ "*" ]

  - level: Metadata
    omitStages:
      - RequestReceived
