apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-nonroot
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - name: tmp
      emptyDir: { }
  containers:
    - name: alpine
      image: alpine:3.20
      command: [ "sh", "-c", "echo 'Hello from non-root'; sleep 3600" ]
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: [ "ALL" ]
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: tmp
          mountPath: /tmp
